name: Release

on:
  push:
    tags:
      - 'v[0-9].[0-9]+.[0-9]+'
      - 'v[0-9].[0-9]+.[0-9]+-dev'

jobs:
  build:
    permissions:
      packages: write
      contents: write
    environment: production
    strategy:
      fail-fast: false
      matrix:
        goos:
          - 'linux'
          - 'windows'
          - 'darwin'
        goarch:
          - 'amd64'
          - 'arm64'
        go:
          - '1.22'

        include:
        # Set the minimum Go patch version for the given Go minor
        # Usable via ${{ matrix.GO_SEMVER }}
        - go: '1.22'
          GO_SEMVER: '~1.22.1'

    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      FILENAME: sbom2vans
      SRC_DIR: ./cmd/sbom2vans
      RELEASE_TAG: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          go-version-patch: ${{ matrix.GO_SEMVER }}

      - name: Build and Compress Binary
        run: |
          # binary suffix
          EXT=''
          if [ "${{ matrix.goos }}" = "windows" ]; then
            EXT='.exe'
          fi

          # Build the binary with a fixed filename
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ${{ env.FILENAME }}$EXT ${{ env.SRC_DIR }}

          # Compress the binary based on the OS
          if [ "${{ matrix.goos }}" = "windows" ]; then
            zip -vr ${{ env.FILENAME }}-${{ RELEASE_TAG }}-${{ matrix.goos }}-${{ matrix.goarch }}.zip ${{ env.FILENAME }}$EXT
          else
            tar cvfz ${{ env.FILENAME }}-${{ RELEASE_TAG }}-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz ${{ env.FILENAME }}$EXT
          fi
